USE pds;

SELECT COUNT(distinct JOB_ID) AS COUNT_OF_JOB
FROM employees;

SELECT AVG(SALARY) AS AVG_SALARY, COUNT(EMPLOYEE_ID) AS COUNT_EMPLOYEE
FROM employees
WHERE DEPARTMENT_ID = 90;

SELECT distinct JOB_ID, COUNT(EMPLOYEE_ID) AS COUNT_EMPLOYEE
FROM employees
GROUP BY JOB_ID;

SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID
FROM employees
GROUP BY EMPLOYEE_ID;

SELECT FIRST_NAME, jobs.JOB_TITLE, employees.DEPARTMENT_ID, locations.CITY
FROM employees LEFT JOIN jobs
ON 	employees.JOB_ID = jobs.JOB_ID
LEFT JOIN departments
ON 	employees.DEPARTMENT_ID = departments.DEPARTMENT_ID
LEFT JOIN locations
ON departments.LOCATION_ID = locations.LOCATION_ID
WHERE CITY = 'london';

